### ISSUE TITLE
Create ChemCrow/Langchain plugin for Semantic Scholar

### ISSUE THREAD

**Issue by saddlerto** [NCBI-Codeathons/mlxai-2024-team-saddler#6]
- [Semantic Scholar Homepage](https://www.semanticscholar.org/)
- [Semantic Scholar API Documentation](https://www.semanticscholar.org/product/api)

**Comment by boratyng** [comment]
ToxPipe is querying Semantic Scholar via `Scholar2ResultsLLM` tool and `paperscrapper`, thanks to @vestalisvirginis.
